bundler_args: "--without debug"
cache: bundler
script: bundle exec rake test
dist: focal
rvm:
  - 2.6.7
  - 2.7.3
  - 3.0.1
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile

matrix:
  exclude:
    - rvm: 3.0.1
      gemfile: gemfiles/rails_5.gemfile

addons:
  code_climate:
    repo_token:
      secure: WBszVdtEvWM2KugFre9BpwkCduY6hjrmK7xo1GLiru4NMqr4ZoRXruQ5ijhZE79YqduR6zudKr72g9yG4R+4CK7ghYu4x5JB76IW8gFWpI9teTWrF4hdSbJgwxSH5JNkqWF4f6ic4Xr1Vgc43agzt+1KmA9imoGs2Q0EbAY3H2M=
